spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_users
    username: banking_user
    password: banking_pass
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
