spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_users
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
